export function About() {
  return (
    <div style={{ maxWidth: "800px", margin: "0 auto" }}>
      <h1>Creation</h1>
      <h2>About this page</h2>
      <p>
        This page/project is a space for me to explore procedural generation and
        worldbuilding techniques. It is partly inspired by the works of Tolkein
        and games like Dwarf Fortress, where a deep history of the fictional
        world runs far back in time and has implications for the current state.
      </p>
      <p>
        There are a few aspects which I find particularly interesting to
        explore:
      </p>
      <ul>
        <li>The creation and shaping of terrain.</li>
        <li>The composition of language and its evolution over time.</li>
        <li>
          How an abstract "creation myth" ties into a timeline that becomes more
          grounded.
        </li>
      </ul>
      <p>
        I am not trying to build a game or a specific simulation. This is just
        recreational programming to explore these domains.
      </p>
      <h2>How it works</h2>
      <p>
        <em>This section might not ever be complete or up-to-date.</em>
      </p>
      <h3>Simulation</h3>
      <p>
        The simulation currently runs over 100 time steps, called ticks. By
        default the entire simulation runs on page-load, this can be controlled
        using the playback controls at the top of the page.
      </p>
      <p>
        Everything within the simulation is generated on page-load. You can
        reload the page to generate an entirely new world.
      </p>
      <h3>Terrain</h3>
      <p>
        The terrain is generated by combining multiple ocataves of perlin noise,
        which determine aspects like height, roughness etc. Biomes and features
        like continents are calculated from these initial values.
      </p>
      <h3>Beings</h3>
      <p>
        Beings are placed in the world. At the moment deities are the only
        category of beings. During each tick beings can:
      </p>
      <ul>
        <li>
          Decide which action to perform (if not currently performing one).
        </li>
        <li>Progress through the chosen action.</li>
      </ul>
      <p>
        Beings have a set of needs, and will decide to perform actions based on
        proximity, the current level of need, and preferences. Beings can
        pathfind to actions that are not located in their current region.
      </p>
      <p>Actions can:</p>
      <ul>
        <li>Take time to complete</li>
        <li>Be undertaken by multiple beings</li>
        <li>Be interrupted</li>
        <li>Be joined by beings who were not present when they started</li>
      </ul>
      <p>
        The current set of actions includes conversation, creation/gifting of
        artifacts and creation of locations.
      </p>
      <h3>Artifacts</h3>
      <p>
        Artifacts are named objects in the world created by deities. They can be
        composed of a number of parts, each made of different materials.
      </p>
      <h3>Language</h3>
      <p>
        An intitial language is created for the world. This is used to generate
        names for beings and artifacts. The language is governed by phonotactics
        which represent the set of available phonemes or sounds.
      </p>
      <p>
        Words are displayed as they would be pronounced using the international
        phonetic alphabet. Words are derived from common roots, so a sword
        created by a deity will could have a similar name.
      </p>
      <h3>Logs</h3>
      <p>
        Logs are captured for most events within the simulation. These can be
        viewed and filtered for the whole world, or inspected for a specific
        region/artifact/being by clicking the magnifying glass icons throughout
        the page.
      </p>
    </div>
  );
}
