export const config = {
  runTicks: 75,
  preRegisterWords: ["the", "of"],
  artifactItems: [
    "sword",
    "shield",
    "dagger",
    "spear",
    "cup",
    "bowl",
    "knife",
    "bracelet",
    "necklace",
    "chain",
    "rope",
    "gown",
    "robe",
    "club",
    "scepter",
    "vial",
    "hood",
    "veil",
    "necklace",
    "eyeglass",
    "map",
  ],
  deityCount: 4,
  noMovementChance: 0.6,
  worldWidth: 5,
  worldHeight: 5,
};
